<?php
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");


//require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");
$APPLICATION->SetTitle("");
?><?

$APPLICATION->SetTitle(""); ?><?$APPLICATION->IncludeComponent(
	"bitrix:main.register",
	"registr_form",
	Array(
		"AUTH" => "Y",
		"REQUIRED_FIELDS" => array("EMAIL","NAME"),
		"SEF_FOLDER" => "/",
		"SEF_MODE" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_FIELDS" => array("EMAIL","TITLE","NAME","SECOND_NAME","LAST_NAME","PERSONAL_PROFESSION","PERSONAL_WWW","PERSONAL_ICQ","PERSONAL_GENDER","PERSONAL_BIRTHDAY","PERSONAL_PHOTO","PERSONAL_PHONE","PERSONAL_FAX","PERSONAL_MOBILE","PERSONAL_PAGER","PERSONAL_STREET","PERSONAL_MAILBOX","PERSONAL_CITY","PERSONAL_STATE","PERSONAL_ZIP","PERSONAL_COUNTRY","PERSONAL_NOTES","WORK_COMPANY","WORK_DEPARTMENT","WORK_POSITION","WORK_WWW","WORK_PHONE","WORK_FAX","WORK_PAGER","WORK_STREET","WORK_MAILBOX","WORK_CITY","WORK_STATE","WORK_ZIP","WORK_COUNTRY","WORK_NOTES"),
		"SUCCESS_PAGE" => "",
		"USER_PROPERTY" => array("UF_INN","UF_KPP","UF_SELECT_FORM","UF_SOGLASIE_FORM"),
		"USER_PROPERTY_NAME" => "",
		"USE_BACKURL" => "Y",
		"VARIABLE_ALIASES" => ""
	)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>